# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=50)),
                ('date_pub', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=40)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('upload_dt', models.DateTimeField(auto_now=True)),
                ('album_name', models.ForeignKey(db_column='album_name', on_delete=django.db.models.deletion.CASCADE, to='photos.Album')),
            ],
        ),
    ]
